apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pdharmavaram-poi-map-app-dev
  annotations:
    argocd/app-name: pdharmavaram-poi-map-app-dev
    backstage.io/kubernetes-id: pdharmavaram-poi-map-app
    backstage.io/kubernetes-namespace: pdharmavaram
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-atl/pdharmavaram-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/dev-pipelines/ns/pdharmavaram/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/k8s/ns/pdharmavaram/deployments/pdharmavaram-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.j0i9yf30.eastus2.aroapp.io/#https://github.com/rhdh-atl/pdharmavaram-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://pdharmavaram-poi-map-app-pdharmavaram.apps.j0i9yf30.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/pdharmavaram"
  system: workshop-system-pdharmavaram
  consumesApis:
    - gateway-api-pdharmavaram
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-pdharmavaram
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/pdharmavaram"
